using Silk.NET.OpenGL.Legacy;

namespace BetaSharp.Client.Rendering.Core;

public unsafe interface IGL
{
    void AlphaFunc(GLEnum func, float refValue);
    void AttachShader(uint program, uint shader);
    void BindBuffer(GLEnum target, uint buffer);
    void BindTexture(GLEnum target, uint texture);
    void BindVertexArray(uint array);
    void BlendFunc(GLEnum sfactor, GLEnum dfactor);
    void BufferData<T0>(GLEnum target, ReadOnlySpan<T0> data, GLEnum usage) where T0 : unmanaged;
    void BufferData(GLEnum target, nuint size, void* data, GLEnum usage);
    void CallList(uint list);
    void CallLists(uint n, GLEnum type, void* lists);
    void Clear(ClearBufferMask mask);
    void ClearColor(float red, float green, float blue, float alpha);
    void ClearDepth(double depth);
    void Color3(float red, float green, float blue);
    void Color3(byte red, byte green, byte blue);
    void Color4(float red, float green, float blue, float alpha);
    void ColorMask(bool red, bool green, bool blue, bool alpha);
    void ColorMaterial(GLEnum face, GLEnum mode);
    void ColorPointer(int size, ColorPointerType type, uint stride, void* pointer);
    void CompileShader(uint shader);
    uint CreateProgram();
    uint CreateShader(ShaderType type);
    void CullFace(GLEnum mode);
    void DeleteBuffer(uint buffer);
    void DeleteLists(uint list, uint range);
    void DeleteProgram(uint program);
    void DeleteShader(uint shader);
    void DeleteTexture(uint texture);
    void DeleteTextures(uint n, ReadOnlySpan<uint> textures);
    void DeleteTextures(ReadOnlySpan<uint> textures);
    void DeleteVertexArray(uint array);
    void DepthFunc(GLEnum func);
    void DepthMask(bool flag);
    void Disable(EnableCap cap);
    void Disable(GLEnum cap);
    void DisableClientState(GLEnum array);
    void DrawArrays(GLEnum mode, int first, uint count);
    void Enable(GLEnum cap);
    void EnableClientState(GLEnum array);
    void EnableVertexAttribArray(uint index);
    void EndList();
    void Fog(GLEnum pname, float param);
    void Fog(GLEnum pname, ReadOnlySpan<float> params_);
    void Frustum(double left, double right, double bottom, double top, double zNear, double zFar);
    uint GenBuffer();
    void GenBuffers(uint n, Span<uint> buffers);
    void GenBuffers(Span<uint> buffers);
    uint GenLists(uint range);
    uint GenTexture();
    void GenTextures(Span<uint> textures);
    uint GenVertexArray();
    GLEnum GetError();
    void GetFloat(GLEnum pname, Span<float> data);
    void GetFloat(GLEnum pname, out float data);
    void GetFloat(GLEnum pname, float* data);
    void GetProgram(uint program, ProgramPropertyARB pname, out int params_);
    string GetProgramInfoLog(uint program);
    void GetShader(uint shader, ShaderParameterName pname, out int params_);
    string GetShaderInfoLog(uint shader);
    int GetUniformLocation(uint program, string name);
    bool IsExtensionPresent(string extension);
    void Light(GLEnum light, GLEnum pname, float* params_);
    void LightModel(GLEnum pname, float* params_);
    void LineWidth(float width);
    void LinkProgram(uint program);
    void LoadIdentity();
    void MatrixMode(GLEnum mode);
    void NewList(uint list, GLEnum mode);
    void Normal3(float nx, float ny, float nz);
    void NormalPointer(NormalPointerType type, uint stride, void* pointer);
    void Ortho(double left, double right, double bottom, double top, double zNear, double zFar);
    void PixelStore(PixelStoreParameter pname, int param);
    void PolygonOffset(float factor, float units);
    void PopMatrix();
    void PushMatrix();
    void ReadPixels(int x, int y, uint width, uint height, PixelFormat format, PixelType type, void* pixels);
    void Rotate(float angle, float x, float y, float z);
    void Scale(float x, float y, float z);
    void Scale(double x, double y, double z);
    void Scissor(int x, int y, uint width, uint height);
    void ShadeModel(GLEnum mode);
    void ShaderSource(uint shader, string string_);
    void TexCoordPointer(int size, GLEnum type, uint stride, void* pointer);
    void TexImage2D(TextureTarget target, int level, InternalFormat internalformat, uint width, uint height, int border, PixelFormat format, PixelType type, void* pixels);
    void TexImage2D(GLEnum target, int level, int internalformat, uint width, uint height, int border, GLEnum format, GLEnum type, void* pixels);
    void TexParameter(TextureTarget target, TextureParameterName pname, int param);
    void TexParameter(GLEnum target, GLEnum pname, int param);
    void TexParameter(GLEnum target, GLEnum pname, float param);
    void TexSubImage2D(GLEnum target, int level, int xoffset, int yoffset, uint width, uint height, GLEnum format, GLEnum type, void* pixels);
    void Translate(float x, float y, float z);
    void Uniform1(int location, int v0);
    void Uniform1(int location, float v0);
    void Uniform2(int location, float v0, float v1);
    void Uniform3(int location, float v0, float v1, float v2);
    void Uniform4(int location, float v0, float v1, float v2, float v3);
    void UniformMatrix4(int location, uint count, bool transpose, float* value);
    void UseProgram(uint program);
    void VertexAttribIPointer(uint index, int size, GLEnum type, uint stride, void* pointer);
    void VertexAttribPointer(uint index, int size, GLEnum type, bool normalized, uint stride, void* pointer);
    void VertexPointer(int size, GLEnum type, uint stride, void* pointer);
    void Viewport(int x, int y, uint width, uint height);
}
